### ISSUE TITLE
Importing etree misses libxslt

### ISSUE THREAD

**Issue by blankclemens** [conda-forge/lxml-feedstock#12]
Hello everyone,

when installing `lxml` in a Python 2 environment I cannot import `etree` from it:

```
from lxml import etree                                                                             │
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```
There is a package `libiconv` on conda-forge which will change this issue to `libicui18n.so.58` being the missing one.

I assume this is not really related to the package itself but rather conda or the underlying system, but I also don't know where better to ask. ;-)

Happens on Ubuntu 16.04 and it's possible to work around by using Python outside a conda environment with the apt lxml package.

**Comment by blankclemens** [comment]
Looking at #10 I found that installing the conda-forge package `libxslt` will solve this issue - should that be added to the requirements?

**Comment by ocefpaf** [comment]
Take a look at http://conda-forge.github.io/docs/conda-forge_gotchas.html

Everything should work fine if `conda-forge` has higher preference in your channel list.

**Comment by blankclemens** [comment]
Thanks!
