### ISSUE TITLE
lxml should depend on icu 58

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/lxml-feedstock#14]
Otherwise you get errors like `    ImportError: dlopen(/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib` (e.g., using `icu` from `defaults`).

**Comment by asmeurer** [comment]
Or maybe it should libxslt, the full error is

```
    ImportError: dlopen(/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
      Referenced from: /Users/aaronmeurer/anaconda3/lib/libxslt.1.dylib
      Reason: image not found
```

**Comment by ocefpaf** [comment]
It is `libxml2` that depends on `icu` and `libxml2` is used to build both `libxslt` and `lxml`.

The CIs are doing the right thing, see https://travis-ci.org/conda-forge/lxml-feedstock/jobs/239789593#L482

Can you check if you are getting any package from `defaults`?

**Comment by asmeurer** [comment]
I am getting icu from defaults (I mentioned that above). That's why the dependency in the package should specify a version, so that it installs the right one.

**Comment by asmeurer** [comment]
(and more generally, it would be nice if conda-forge automatically or semi-automatically detected these version dependencies from the linkages and added them to the packages)

**Comment by asmeurer** [comment]
Apparently libxslt isn't even depending on icu at all. I just happened to have it installed. See https://github.com/conda-forge/libxslt-feedstock/issues/8.This should probably be closed in favor of that issue, since `lxml` doesn't link against icu directly:

```
$conda inspect linkages lxml
lxml
----

libxml2-2.9.4-0:
    libxml2.2.dylib (lib/libxml2.2.dylib)

libxslt-1.1.29-3:
    libexslt.0.dylib (lib/libexslt.0.dylib)
    libxslt.1.dylib (lib/libxslt.1.dylib)

zlib-1.2.11-0:
    libz.1.dylib (lib/libz.1.dylib)

system:
    libSystem.B.dylib (/usr/lib/libSystem.B.dylib)

not found:
```
