### ISSUE TITLE
etree_api.h seems to be missing

### ISSUE THREAD

**Issue by pakelley** [conda-forge/lxml-feedstock#20]
Hi there, I'm not sure if this is the right place to ask this, but I'm happy to post somewhere else if there's a better place :)

Anyway, I'm running into issues with a Cython project using `lxml.etree`, but when it compiles it complains that it can't find `etree_api.h`. It looks like there is a `lxml.etree_api.h` in the directory installed by the lxml package, and it successfully installs if I move the file to `etree_api.h`.

Also, this was compiling without error before. Have there been any recent changes to this file?

**Comment by ocefpaf** [comment]
The file is present and I'm guess we would need to check your building configuration to find out what wrong there.
