### ISSUE TITLE
linux: missing runtime-dependency libiconv.so.2

### ISSUE THREAD

**Issue by looooo** [conda-forge/lxml-feedstock#24]
Tests for [openglider](https://travis-ci.org/booya-at/OpenGlider/jobs/400864571#L1221) are failing recently because libiconv.so.2 is missing. I guess we should add `libiconv` to the dependencies of this feedstock.

**Comment by mariusvniekerk** [comment]
Yep

**Comment by mariusvniekerk** [comment]
There is a PR open for a version bump which will pull in the new libxml2 which has run_exports enabled which should fix this

**Comment by ocefpaf** [comment]
Not really. It may only need a re-build. Let's see if #23 fixes this.

**Comment by ocefpaf** [comment]
@mariusvniekerk the Linux builds did not make into the channel b/c the CircleCI token was expired. I just send #25 to fix this and I'm restarting the CIs. After that let me know if you are still experiencing this issue.

**Comment by ocefpaf** [comment]
I merged https://github.com/conda-forge/libxml2-feedstock/pull/36 and I'm re-triggering the CIs now.

**Comment by looooo** [comment]
thanks. I can confirm, this fixed this issue.
